export * from './addLog';
export * from './extractHintedSelector';
export * from './extractDialogExpectation';
export * from './finalizeSelector';
export * from './matchesPattern';
export * from './extractUrl';
export * from './extractQuotedText';
export { extractGeneralSelector } from './extractGeneralSelector';
export { extractGeneralSelector as extractSelector } from './extractGeneralSelector';
export { extractGeneralSelector as extractSpecificSelector } from './extractGeneralSelector';
export * from './extractValue';
export * from './extractInputField';
export * from './extractDropdownField';
export * from './extractScrollTarget';
export * from './extractTimeout';
export * from './getInputType';
export * from './getFieldName'; 