name: Build & Push Discord-Bot Image

on:
  push:
    branches: [ main ]      # build every time main is updated

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ----- Docker Hub login -----
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" |
             docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ----- Build & push image -----
      - name: Build image
        run: docker build -f docker/bot.Dockerfile -t labnexdev/labnex-bot:latest ./backend

      - name: Push image
        run: docker push labnexdev/labnex-bot:latest

      # ----- Tell Render to pull the new image -----
      - name: Trigger Render deploy
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_BOT_DEPLOY_HOOK }}
        run: curl -fsSL -X POST "$RENDER_DEPLOY_HOOK" 