name: Build & Push Discord Bot Image

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'bots/**'
      - 'docker/bot.Dockerfile'
      - '.github/workflows/build-push-bot.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push bot image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: docker/bot.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/labnex-bot:latest 