name: "SEO & Lighthouse Audit"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run Lighthouse CI on production URL
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: .lighthouserc.json
          artifactName: lhci_${{ github.run_id }}
          uploadArtifacts: true
          temporaryPublicStorage: true 